/**
 * Database Migration Runner
 *
 * Runs Drizzle migrations on startup so deployments always
 * have up-to-date schema without a manual step.
 *
 * Strategy:
 *   - In production: runs migrations from the ./migrations folder (generated by drizzle-kit)
 *   - In development: skips (use `npm run db:push` instead for speed)
 *
 * Called from server/index.ts before registerRoutes().
 */

import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";
import { existsSync } from "fs";
import { join } from "path";

export async function runMigrations(): Promise<void> {
  if (!process.env.DATABASE_URL) {
    console.warn("⚠️  DATABASE_URL not set — skipping migrations.");
    return;
  }

  // Resolve migrations folder strictly relative to execution root
  const migrationsFolder = join(process.cwd(), "migrations");

  if (!existsSync(migrationsFolder)) {
    console.warn(
      "⚠️  migrations/ folder not found. Run `npm run db:migrate` to generate migrations, " +
      "or `npm run db:push` for a quick dev schema push."
    );
    return;
  }

  // Unix socket connections don't use SSL
  const isUnixSocket = (process.env.DATABASE_URL || "").includes("host=/");
  const pool = new Pool({ 
    connectionString: process.env.DATABASE_URL,
    ssl: isUnixSocket ? false : (process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : false),
    connectionTimeoutMillis: 15_000,
  });

  // Prevent unhandled pool errors from crashing the process
  pool.on("error", (err) => {
    console.error("Migration pool error on idle client:", err.message);
  });

  try {
    console.log("🗄️  Running database migrations...");
    const db = drizzle(pool);
    await migrate(db, { migrationsFolder });
    console.log("✅ Migrations complete.");
  } catch (err: any) {
    // Log the full error for debugging, but do NOT process.exit().
    // The schema may already exist from a previous deploy.
    // Crashing here prevents the container from ever binding to PORT,
    // which triggers the "container failed to start" loop.
    console.error("❌ Migration failed (non-fatal, server will attempt to start):", err.message);
    if (err.stack) {
      console.error("  Stack:", err.stack);
    }
  } finally {
    await pool.end();
  }
}
