/**
 * Database Migration Runner
 *
 * Runs Drizzle migrations on startup so Cloud Run deployments always
 * have up-to-date schema without a manual step.
 *
 * Strategy:
 *   - In production: runs migrations from the ./migrations folder (generated by drizzle-kit)
 *   - In development: skips (use `npm run db:push` instead for speed)
 *
 * Called from server/index.ts before registerRoutes().
 */

import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";
import { existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

export async function runMigrations(): Promise<void> {
  if (!process.env.DATABASE_URL) {
    console.warn("⚠️  DATABASE_URL not set — skipping migrations.");
    return;
  }

  // Resolve migrations folder relative to this file
  const migrationsFolder = join(__dirname, "..", "migrations");

  if (!existsSync(migrationsFolder)) {
    console.warn(
      "⚠️  migrations/ folder not found. Run `npm run db:migrate` to generate migrations, " +
      "or `npm run db:push` for a quick dev schema push."
    );
    return;
  }

  const pool = new Pool({ connectionString: process.env.DATABASE_URL });

  try {
    console.log("🗄️  Running database migrations...");
    const db = drizzle(pool);
    await migrate(db, { migrationsFolder });
    console.log("✅ Migrations complete.");
  } catch (err: any) {
    console.error("❌ Migration failed:", err.message);
    // In production, a failed migration is fatal — we can't serve stale schema
    if (process.env.NODE_ENV === "production") {
      process.exit(1);
    }
  } finally {
    await pool.end();
  }
}
